version: "3.7"
services:
  consul:
    image: consul:1.2.3
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
  message-uuid-generator:
    build: message-uuid-generator
    image: messuuid:latest
    deploy:
      replicas: 2
    ports:
      - "8081:8081"
    expose:
      - "8081"
    depends_on:
      - consul
    links:
      - consul
  message-processor:
    build: message-processor
    image: messproc:latest
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      - consul
      - message-uuid-generator
    links:
      - consul
      - message-uuid-generator


